name: Deploy Website

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Download Repository
              uses: actions/checkout@v4
            
            - name: Create SSH key
              run: |
                echo "${{ secrets.SSH_KEY }}" > key.pem
                chmod 600 key.pem

            - name: log in to EC2
              run: |
                ssh -o StrictHostKeyChecking=no -i  key.pem ${{secrets.USER}}@${{secrets.HOST}} "cd ~/redux && git pull && docker compose down && docker compose up --build -d"
